### ISSUE TITLE
Ublock origin blocks the IP being displayed

### ISSUE THREAD

**Issue by Frostbite952** [rdegges/ipify-api#18]
While having Ublock origin enabled the IP no longer appears on the webpage. Currently building a web app using MVC Core and ipify was embedded on the page using JS.

**Comment by rdegges** [comment]
Oo I wonder why? Can you paste the code you were using? ublock tends to look for certain HTML element names and uses those to block ads, etc. (in addition to domain blacklists).

**Comment by Frostbite952** [comment]
It could be down to how I have embedded it on the page. I added it to a pastebin for you -https://pastebin.com/TbAhf7Vb

**Comment by captainfodder** [comment]
I actually have this same issue with one of my websites.  Here is a rough idea pastebin as well: https://pastebin.com/gSubrd99

**Comment by JamesIsNinja** [comment]
I am experiencing the same problem actually, did anyone find a solution? Pastebin of my code:
https://pastebin.com/iGeAJyG4

**Comment by NathanCollaert** [comment]
Same problem, ublocker is blocking ipify from giving me the user's IP.

**Comment by szepeviktor** [comment]
Actually `||ipify.org^$third-party` is in https://easylist.to/easylist/easyprivacy.txt

**Comment by addow** [comment]
I can confirm, I ended up in the same situation. Ublocker is blocking ipify.org API requests.
It's on the easyprivacy list as @szepeviktor mentioned, so it is blocked probably because the request is coming from another website (domain).

We can whitelist it of coure, but why is it blocked in the first place. It's just a simple API for retrieving a user's IP address. Ipify does not do any tracking or violate the user's privacy, right?

**Comment by szepeviktor** [comment]
If you do not track your visitors you do not need their IP!

**Comment by addow** [comment]
> If you do not track your visitors you do not need their IP!

I use it the determine the public IP of cloud instances (LXC containers, docker instances), not visitors :wink:

**Comment by JamesIsNinja** [comment]
> If you do not track your visitors you do not need their IP!

Our purpose was not tracking, but rather verification, only users within a certain IP Range should be allowed to access a resource from our page, the only way to know if they fall within that IP range is to use a service like IPify or write a custom solution to ensure they are in the physical location allowed to access the resource.

**Comment by rdegges** [comment]
Unfortunately, there's nothing much I can really do about this.

Here's the fact of it: from an adblocker perspective, they try to reduce the amount of third-party JS that runs in the browser used for tracking or advertising purposes. Since ipify allows you to get a user's IP address, that means technically some people might use it for that use case. So this is why an adblocker may block something like ipify.

Now, obviously, it would be great if someone could make the argument that ipify is a standalone service that has nothing whatsoever to do with tracking, and get it removed from the filter list.

But I'd also say that any developer who *does* want to track their users is definitely doing it wrong by using ipify. IP addresses aren't a great way to bind to a user since they change all the time and typically aren't 1:1 with a device. It's a crappy way to track or ID someone and super unreliable. That's why you have services like Google Analytics, etc. -- they use a ton of heuristics to track.

**Comment by brainkim** [comment]
Just ran into this. This is a bit of a shame. Here’s the issue in easylist https://github.com/easylist/easylist/issues/2810. Maybe a maintainer can convince them to change their minds?
